### ISSUE TITLE
Hope to support Reactivity transform

### ISSUE THREAD

**Issue by XioDone** [vitejs/vite-plugin-vue2#13]
My project builds on ```@vue/composition-api``` and ```unplugin-vue2-script-setup```,
```unplugin-vue2-script-setup``` has  reactivityTransform option
``` 
ScriptSetup({
      reactivityTransform: true
 })
```
It has used a lot of ```$ref```, upgrade to vue 2.7 hope to support reactivity transform. Thanks.

——————————————————————————————————————————————————————————————

我的项目使用```@vue/composition-api``` 和 ```unplugin-vue2-script-setup```构建，
```unplugin-vue2-script-setup```具有 reactivityTransform 选项
``` 
ScriptSetup({
      reactivityTransform: true
 })
```
已经大量使用了```$ref```，升级到 vue 2.7 希望可以支持 reactivity transform，谢谢。

**Comment by sxzz** [comment]
#12609

**Comment by darren-outdev** [comment]
Desperately need this 🙏 Will help the transition from 2.7 to 3 so much

**Comment by sxzz** [comment]
We have to wait until Reactivity Transform is a stable feature and is released in v3.3.

**Comment by TonyYanOnFire** [comment]
Currently using webpack + Vue2.7,  everything is great but the ".value" thing.  Hope Vue2 can support Reactivity Transform ASAP

**Comment by sxzz** [comment]
Released in `unplugin-vue-macros@1.2.0`
https://vue-macros.sxzz.moe/

**Comment by TonyYanOnFire** [comment]
> 

Great job ! Could you provide a more detailed doc? thx

**Comment by sxzz** [comment]
You can refer to the examples
- [Vue CLI](https://github.com/vue-macros/vue2-vue-cli/commit/1d9c7994c4d57aa83fdf52ea635e6ea92336c6bd)
- [Vite](https://github.com/sxzz/unplugin-vue-macros/blob/main/playground/vue2/vite.config.ts)

**Comment by TonyYanOnFire** [comment]
> You can refer to the examples
> 
> * [Vue CLI](https://github.com/vue-macros/vue2-vue-cli/commit/1d9c7994c4d57aa83fdf52ea635e6ea92336c6bd)
> * [Vite](https://github.com/sxzz/unplugin-vue-macros/blob/main/playground/vue2/vite.config.ts)

It appears that the unplugin-vue-macros@1.2.0 is not compatible with webpack, but the latest v1.2.2 seems to work well. It took me a while to figure that out.  😅 thank you all the way and I wish you a happy new year

**Comment by sxzz** [comment]
Reactivity Transform has been dropped officially. @XioDone We can close this issue, and try Vue Macros https://vue-macros.sxzz.moe/features/reactivity-transform.html
