### ISSUE TITLE
vite-plugin-vue2 does not support some components of ElementUI 

### ISSUE THREAD

**Issue by fychinesepjj** [vitejs/vite-plugin-vue2#16]
vue@2.7 和 ElementUI@2.15 可以通过 vue-cli **正常打包与渲染**（ webpack，[参考的官方文档](https://blog.vuejs.org/posts/vue-2-7-beta.html) ）
但切换成 vite  +vite-plugin-vue2 后，部分组件如 `el-table`则**无法渲染且无任何异常错误**。
这个问题通过 webpack 就打包不存在问题，所以推断 `vite-plugin-vue2` 可能存在 bug，希望 Evan You 在百忙之中抽空看下。

dependencies
``` javascript
  "dependencies": {
    "element-ui": "^2.15.9",
    "vue": "^2.7.0-beta.8"
  },
  "devDependencies": {
    "@vitejs/plugin-vue2": "^1.1.1",
    "vite": "^2.9.12"
  }
```

index.html
``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vue2 Vite App</title>
</head>
<body>
  <div id="app"></div>
  <script type="module" src="/src/main.js"></script>
</body>
</html>
```

main.js
``` javascript
import 'element-ui/lib/theme-chalk/index.css';

import Vue from 'vue'
import ElementUI from 'element-ui';
import App from './App.vue'

Vue.config.productionTip = false
Vue.use(ElementUI);

new Vue({
  render: h => h(App),
}).$mount('#app')

```

table component
``` jsx
<template>
    <el-table
      :data="tableData"
      style="width: 100%">
      <el-table-column
        prop="date"
        label="日期"
        width="180">
      </el-table-column>
      <el-table-column
        prop="name"
        label="姓名"
        width="180">
      </el-table-column>
      <el-table-column
        prop="address"
        label="地址">
      </el-table-column>
    </el-table>
  </template>

  <script>
    export default {
      data() {
        return {
          tableData: [{
            date: '2016-05-02',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1518 弄'
          }, {
            date: '2016-05-04',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1517 弄'
          }, {
            date: '2016-05-01',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1519 弄'
          }, {
            date: '2016-05-03',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1516 弄'
          }]
        }
      }
    }
  </script>
```

![image](https://user-images.githubusercontent.com/5492785/176409067-c829f7fd-006c-45ff-ab2b-a2f6feab8fb0.png)
![image](https://user-images.githubusercontent.com/5492785/176412707-38b80c07-a994-4ab3-ba23-ddc3cda93bea.png)

**Comment by yyx990803** [comment]
根本原因是 element-ui 用的是 cjs 语法然后 require 了 vue，导致它引用了 cjs 版本的 vue，而你的主应用跑的是 esm 版本的 vue（实际上等于应用里跑了两个 Vue）

这个情况在 Vue 3 依赖里比较少见，可以通过默认强行制定 vue 的解析路径解决。

fixed in 1.1.2

**Comment by fyeeme** [comment]
上次也碰到了，以为是因为beta版本导致，没有在意。

**Comment by jetBn** [comment]
> @yyx990803 感谢尤大的回复～，这个细节我确实没注意到。 @fyeeme 也是对比 webpack 和 vite 两种打包方式后，才确认不是 Vue2.7 beta的问题，ElementUI 嫌疑更大

最后咋解决的呀？

**Comment by anyesu** [comment]
[commit/9a78726](https://github.com/vitejs/vite-plugin-vue2/commit/9a78726d77ef9aadf3c07dacd4c27828fe8f4ac8) 改完后还是有问题，开发模式能显示 `el-table` 了，但打包后显示不出来。

```
"vue": "2.7.14"
"vite": "4.4.9"
"@vitejs/plugin-vue2": "2.2.0"
"element-ui": "2.15.13"
```

**debug** 后发现，**@rollup/plugin-alias** 在 [resolvePlugins](https://github.com/vitejs/vite/blob/9b7b4ed99ff30ca8eed520233b89e5f977015656/packages/vite/src/node/plugins/index.ts#L55) 和 [createResolver](https://github.com/vitejs/vite/blob/9b7b4ed99ff30ca8eed520233b89e5f977015656/packages/vite/src/node/config.ts#L609) 两处地方实例化，只有在 **createResolver** 中拿到的 `resolve.alias` 是修改后的预期值，而 [resolvePlugins 在 configResolved 之前执行](https://github.com/vitejs/vite/blob/9b7b4ed99ff30ca8eed520233b89e5f977015656/packages/vite/src/node/config.ts#L743-L776) ，所以拿到的 `resolve.alias` 是修改前的原始值。这两处地方入参不一致应该会有问题，但开发模式竟然能正常运行而打包模式不行，就很奇怪。

而且，按照 **Vite** 文档描述的，修改 `resolve.alias` 的代码应该写在 [config](https://cn.vitejs.dev/guide/api-plugin.html#config) 钩子而不是 [configResolved](https://cn.vitejs.dev/guide/api-plugin.html#configresolved) 钩子中：

```typescript
const elementUiVueAliasPlugin = (): VitePlugin => ({
  name: 'element-ui-vue-alias',
  config(config) {
    const alias = config.resolve?.alias;
    if (!alias) {
      return {
        resolve: {
          alias: {
            vue: 'vue/dist/vue.runtime.esm.js'
          }
        }
      } as UserConfig;
    }

    if (Array.isArray(alias) && !alias.some(({ find }) => find === 'vue')) {
      alias.push({
        find: 'vue',
        replacement: 'vue/dist/vue.runtime.esm.js'
      });
    } else if (!alias['vue']) {
      alias['vue'] = 'vue/dist/vue.runtime.esm.js';
    }

    return null;
  }
});
```

临时解决办法就是项目配置中手写 `resolve.alias` ：（ [参考](https://github.com/ElemeFE/element/issues/21984#issuecomment-1581740075) ）

```diff
// vite.config.ts
export default defineConfig({
  resolve: {
    alias: [
+     {
+       find: 'vue',
+       replacement: 'vue/dist/vue.runtime.esm.js'
+     }
    ]
  }
});
```

**Comment by guozhenyi** [comment]
我在element-ui打的包里看到了这个，但是在element-ui的源代码里没看到这种导入语句
![Image](https://github.com/user-attachments/assets/a41c9194-66e4-4875-b91c-cc05f246e475)

**Comment by lisonge** [comment]
我在 `vite@5.4.10`+`@vitejs/plugin-vue2@2.3.1` 没有遇见这个问题

但是升级到了  `vite@6.2.1`+`@vitejs/plugin-vue2@2.3.3` 竟然遇见了这个问题 

解决方法也是上面说的 <https://github.com/vitejs/vite-plugin-vue2/issues/16#issuecomment-1680297553>
