### ISSUE TITLE
Package version is not correctly displayed in vue ui

### ISSUE THREAD

**Issue by Threnos** [vitejs/vite-plugin-vue2#32]
When looking at your package in vue ui it does not show current version and thinks that there is an update, when in fact I am on the latest version 1.1.2.

![image](https://user-images.githubusercontent.com/30055497/181749123-e6c0320b-5949-4c94-800d-3d25d0e00e91.png)

**Comment by yyx990803** [comment]
This is a bug in Vue CLI's UI feature, not a problem of this plugin itself.
