### ISSUE TITLE
script setup with tsx compile error

### ISSUE THREAD

**Issue by troy351** [vitejs/vite-plugin-vue2#35]
- creating a vue project via `npm init vue@2`, check only `TypeScript` and `JSX`
- create a component with the following code
   ```vue
  <script lang="tsx" setup>
    import { defineComponent } from 'vue'
  </script>
  
  <script lang="tsx">
    export default defineComponent({
      render() {
        return <div>demo</div>
      },
    })
  </script>
   ```
- use this component
- run the project

compile error
```
[plugin:vite:vue2-jsx] unknown: Missing semicolon. (3:21)
  6 |     },
file/path/CTest.vue:6:16
1  |  import { defineComponent as _defineComponent } from 'vue'
2  |  
3  |  const __default__ = t defineComponent({
   |                       ^
4  |      render() {
5  |        return <div>demo</div>
```

FYI. it works with `h('div', 'demo')` and vue 3.x

**Comment by sodatea** [comment]
Seems no longer reproducible with the latest versions? I guess it's fixed in https://github.com/vuejs/vue/commit/46ca7bcddc06c50796ccff82d8c45693f1f14f47
