### ISSUE TITLE
Support Using Vue SFCs as Custom Elements 

### ISSUE THREAD

**Issue by porfirioribeiro** [vitejs/vite-plugin-vue2#37]
In Vite plugin for Vue3 it's possible to compile Vue SFC's and get the CSS to inject inside a Custom Element
https://github.com/vitejs/vite/tree/main/packages/plugin-vue#using-vue-sfcs-as-custom-elements

Would be nice to be able to have the same functionality in Vue2

**Comment by sodatea** [comment]
Let's track this issue at https://github.com/vitejs/vite-plugin-vue2/issues/18
