### ISSUE TITLE
slot doesn't work

### ISSUE THREAD

**Issue by ZengTianShengZ** [vitejs/vite-plugin-vue2#39]
my component

```html
// Button.vue
<template>
    <button class="gd-btn">
        <slot>submit</slot>
    </button>
</template>

<style>
.gd-btn{
    width: 80px;
    height: 30px;
    border: 1px solid red;
    background: #fff;
}
</style>
```

use my component
```
<div>
   <Button/>
</div>
```
component does not render default slot content

![image](https://user-images.githubusercontent.com/15622519/182788286-75e827b0-93b8-4faf-a596-32970c1b4579.png)

version:

```
  "vue": "2.7.8"
  "@vitejs/plugin-vue2": "^1.1.2",
  "vite": "^3.0.2",

   node: v16.15.1
   chrome: 103.0.5060.114
```

**Comment by sodatea** [comment]
Can't reproduce.

If the issue still exists, please open a new issue with a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) using a GitHub repository or [StackBlitz](https://stackblitz.com/edit/vitejs-vite-xj3ufp?file=src/App.vue)

**Comment by ZengTianShengZ** [comment]
Sorry, the problem is caused by the version.

my vue version is `2.6.10`

**Comment by patak-dev** [comment]
@ZengTianShengZ vite-plugin-vue2 requires Vue 2.7+
