### ISSUE TITLE
`template.transformAssetUrlsOptions.includeAbsolute: false` has no effect.

### ISSUE THREAD

**Issue by ascott18** [vitejs/vite-plugin-vue2#47]
This is the same issue as https://github.com/vitejs/vite/issues/4836 that was fixed by https://github.com/vitejs/vite/pull/6779 for Vue3.

The following configuration has no effect because it gets [overwritten here](https://github.com/vitejs/vite-plugin-vue2/blob/3b64cccf7fae755bf556876bf85fec5041ed383a/src/template.ts#L123-L125):

```
createVuePlugin({
  template: {
    transformAssetUrlsOptions: {
      includeAbsolute: false,
    },
  },
}),
```

**Comment by patrickdavey** [comment]
I have the same issue. Did you come up with a workaround @ascott18 ?

**Comment by ZeroThe2nd** [comment]
I've got the same issue incorporating Vue 2.7 with Laravel, it's causing import errors on the absolute assets processed by vite.
It's tossing me a console-level error complaining about importing a different MIMEtype as JavaScript.

Unless @ascott18 has a work-around, it might be worth looking into crafting a PR that fixes said issue.

**Comment by ascott18** [comment]
If completely disabling asset transformation will work for your app, then you can do that `({ template: { transformAssetUrls: false, }, })`, but beyond that I don't know of a workaround.

**Comment by rafalglowacz** [comment]
For Laravel devs who run into this issue despite having the newest version of the plugin - try `transformAssetUrlsOptions: {...}` instead of `transformAssetUrls: {...}`. The latter is from current Laravel docs, I guess it's for the Vue 3 plugin or something.

**Comment by albanafmeti** [comment]
> For Laravel devs who run into this issue despite having the newest version of the plugin - try `transformAssetUrlsOptions: {...}` instead of `transformAssetUrls: {...}`. The latter is from current Laravel docs, I guess it's for the Vue 3 plugin or something.

@rafalglowacz worked fine for me. thanks
