### ISSUE TITLE
vite@4 support

### ISSUE THREAD

**Issue by kirillgroshkov** [vitejs/vite-plugin-vue2#71]
vite@4 [was released](https://vitejs.dev/blog/announcing-vite4.html), but this plugin supports vite@^3.0.0

Would be nice to support the latest.

**Comment by khalwat** [comment]
+1 would love to see this

**Comment by khalwat** [comment]
Added a PR to updated `peerDependencies`: https://github.com/vitejs/vite-plugin-vue2/pull/72

**Comment by khalwat** [comment]
In my limited testing, I can confirm that just bumping the `peerDependencies` appears to work fine with Vite 4.x
