### ISSUE TITLE
Lack of JSX syntax support

### ISSUE THREAD

**Issue by yodagg** [vitejs/vite-plugin-vue2#9]
I added some examples to the `playground` and they all work fine.

When I try the JSX syntax via `@vitejs/plugin-vue-jsx`, it throws the error `ERROR: Unterminated regular expression`.

`@vitejs/plugin-vue-jsx` seems to be a `vue3` plugin.

**Comment by ScottAwesome** [comment]
[Per the blog post](https://blog.vuejs.org/posts/vue-2-7-beta.html) 

_Note that the new plugin does not handle Vue-specific JSX / TSX transform, which is intentional. Vue 2 JSX / TSX transform should be handled in a separate, dedicated plugin._

You should just use a babel based plugin for now
